services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: capacity_connect_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY:-AIzaSyAaq8Ft_Bm7ZzRaQc2kWWWQxUvRZaaZxhg}
      - NEO4J_INSTANCE_ID=${NEO4J_INSTANCE_ID:-d84b9a34}
      - NEO4J_URI=${NEO4J_URI:-neo4j+s://d84b9a34.databases.neo4j.io}
      - NEO4J_USERNAME=${NEO4J_USERNAME:-d84b9a34}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-8EZ_zHONjfFm2P39rffJ1wP1lFO-EVl5DHk0QOp3jDU}
    volumes:
      - backend_storage:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: capacity_connect_frontend
    restart: always
    ports:
      - "3000:80"
      - "8080:80"
    depends_on:
      - backend

volumes:
  backend_storage:
