services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: capacity_connect_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - NEO4J_INSTANCE_ID=${NEO4J_INSTANCE_ID}
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    volumes:
      - backend_storage:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: capacity_connect_frontend
    restart: always
    ports:
      - "3000:80"
      - "8080:80"
    depends_on:
      - backend

volumes:
  backend_storage:
